
// Employees
export const employeesData = [
  {
    EmployeeID: 1,
    FullName: "Rahma Sohail",
    CNIC: "35202-1234567-8",
    Email: "rahma@example.com",
    Phone: "03001234567",
    DepartmentID: "IT",
    DesignationID: "Software Engineer",
    JoiningDate: "2022-03-15",
    Salary: 50000,
    Status: "Active",
    Documents: ["CNIC.pdf", "Resume.pdf"],
  },
  {
    EmployeeID: 2,
    FullName: "Ali Raza",
    CNIC: "35201-9876543-2",
    Email: "ali@example.com",
    Phone: "03019876543",
    DepartmentID: "HR",
    DesignationID: "HR Manager",
    JoiningDate: "2021-07-20",
    Salary: 60000,
    Status: "Active",
    Documents: ["CNIC.pdf"],
  },
  {
    EmployeeID: 3,
    FullName: "Ayesha Khan",
    CNIC: "35203-1112233-4",
    Email: "ayesha@example.com",
    Phone: "03031112233",
    DepartmentID: "Finance",
    DesignationID: "Accountant",
    JoiningDate: "2020-01-05",
    Salary: 55000,
    Status: "Inactive",
    Documents: ["CNIC.pdf", "Degree.pdf"],
  },
  {
    EmployeeID: 4,
    FullName: "Usman Malik",
    CNIC: "35204-5556677-1",
    Email: "usman@example.com",
    Phone: "03045556677",
    DepartmentID: "Marketing",
    DesignationID: "Marketing Officer",
    JoiningDate: "2023-06-10",
    Salary: 40000,
    Status: "Active",
    Documents: [],
  },
  {
    EmployeeID: 5,
    FullName: "Hina Fatima",
    CNIC: "35205-8889990-3",
    Email: "hina@example.com",
    Phone: "03058889990",
    DepartmentID: "IT",
    DesignationID: "Intern",
    JoiningDate: "2024-01-01",
    Salary: 20000,
    Status: "Probation",
    Documents: ["CNIC.pdf"],
  },
];

// Payroll
export const payrollData = [
  {
    PayrollID: 101,
    EmployeeID: 1,
    Month: "August 2025",
    BasicSalary: 50000,
    Deductions: 2000,
    Overtime: 5000,
    NetSalary: 53000,
    Archive: "No",
  },
  {
    PayrollID: 102,
    EmployeeID: 2,
    Month: "August 2025",
    BasicSalary: 60000,
    Deductions: 3000,
    Overtime: 2000,
    NetSalary: 59000,
    Archive: "No",
  },
  {
    PayrollID: 103,
    EmployeeID: 3,
    Month: "August 2025",
    BasicSalary: 55000,
    Deductions: 1000,
    Overtime: 0,
    NetSalary: 54000,
    Archive: "Yes",
  },
  {
    PayrollID: 104,
    EmployeeID: 4,
    Month: "August 2025",
    BasicSalary: 40000,
    Deductions: 500,
    Overtime: 1000,
    NetSalary: 40500,
    Archive: "No",
  },
  {
    PayrollID: 105,
    EmployeeID: 5,
    Month: "August 2025",
    BasicSalary: 20000,
    Deductions: 200,
    Overtime: 0,
    NetSalary: 19800,
    Archive: "No",
  },
];

// Performance
export const performanceData = [
  {
    PerformanceID: 201,
    EmployeeID: 1,
    KPIs: "Project Delivery, Code Quality",
    AppraisalDate: "2025-08-31",
    Score: 90,
    Remarks: "Excellent Performance",
  },
  {
    PerformanceID: 202,
    EmployeeID: 2,
    KPIs: "Recruitment, Employee Satisfaction",
    AppraisalDate: "2025-08-31",
    Score: 80,
    Remarks: "Good Work",
  },
  {
    PerformanceID: 203,
    EmployeeID: 3,
    KPIs: "Accounts Management",
    AppraisalDate: "2025-08-31",
    Score: 75,
    Remarks: "Satisfactory",
  },
  {
    PerformanceID: 204,
    EmployeeID: 4,
    KPIs: "Campaigns, Leads",
    AppraisalDate: "2025-08-31",
    Score: 65,
    Remarks: "Needs Improvement",
  },
  {
    PerformanceID: 205,
    EmployeeID: 5,
    KPIs: "Learning, Training",
    AppraisalDate: "2025-08-31",
    Score: 50,
    Remarks: "On Probation, Training Needed",
  },
];

// Fines
export const finesData = [
  {
    ReportID: 301,
    EmployeeID: 1,
    EmployeeName: "Rahma Sohail",
    FineType: "Late Arrival",
    FineAmount: 1000,
    FineDate: "2025-08-10",
    Description: "Arrived late 3 times in a week",
    Status: "Paid",
    Archive: "No",
  },
  {
    ReportID: 302,
    EmployeeID: 2,
    EmployeeName: "Ali Raza",
    FineType: "Leave Without Notice",
    FineAmount: 2000,
    FineDate: "2025-08-12",
    Description: "Took 2 days off without approval",
    Status: "Unpaid",
    Archive: "No",
  },
  {
    ReportID: 303,
    EmployeeID: 3,
    EmployeeName: "Ayesha Khan",
    FineType: "Misconduct",
    FineAmount: 3000,
    FineDate: "2025-08-15",
    Description: "Misbehavior with colleague",
    Status: "Paid",
    Archive: "Yes",
  },
  {
    ReportID: 304,
    EmployeeID: 4,
    EmployeeName: "Usman Malik",
    FineType: "Missed Deadline",
    FineAmount: 1500,
    FineDate: "2025-08-20",
    Description: "Did not submit campaign report",
    Status: "Unpaid",
    Archive: "No",
  },
  {
    ReportID: 305,
    EmployeeID: 5,
    EmployeeName: "Hina Fatima",
    FineType: "Late Arrival",
    FineAmount: 500,
    FineDate: "2025-08-25",
    Description: "Late to office twice",
    Status: "Paid",
    Archive: "No",
  },
];
